[tool.ruff.lint]
extend-select = [
   "F",
    "W",
    "E",
    "N",
    "UP",
    "C4",
    "FA",
    "ISC",
    "ICN",
    "RET",
    "SIM",
]
[tool.ruff]
extend-exclude = ["Tests"]
[tool.ruff.lint]
extend-ignore = ["N999"]
[tool.ruff.lint.pylint]
allow-paths = ["Tests"]
